#pragma once

#include "platform.h"

// can't use 0
#define NVIC_PRIO_MAX                      NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 0, 1)
#define NVIC_PRIO_TIMER                    NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 1, 1)
#define NVIC_PRIO_BARO_EXTI                NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 0x0f, 0x0f)
#define NVIC_PRIO_DSHOT_DMA                NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 2, 1)
#define NVIC_PRIO_MPU_INT_EXTI             NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 0x0f, 0x0f)
#define NVIC_PRIO_MAG_INT_EXTI             NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 0x0f, 0x0f)
#define NVIC_PRIO_SERIALUART_TXDMA         NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 1, 1)  // Highest of all SERIALUARTx_TXDMA
#define NVIC_PRIO_SERIALUART1_TXDMA        NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 1, 1)
#define NVIC_PRIO_SERIALUART1_RXDMA        NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 1, 1)
#define NVIC_PRIO_SERIALUART1              NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 1, 1)
#define NVIC_PRIO_SERIALUART2_TXDMA        NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 1, 0)
#define NVIC_PRIO_SERIALUART2_RXDMA        NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 1, 1)
#define NVIC_PRIO_SERIALUART2              NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 1, 2)
#define NVIC_PRIO_SERIALUART3_TXDMA        NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 1, 0)
#define NVIC_PRIO_SERIALUART3_RXDMA        NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 1, 1)
#define NVIC_PRIO_SERIALUART3              NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 1, 2)
#define NVIC_PRIO_SERIALUART4_TXDMA        NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 1, 0)
#define NVIC_PRIO_SERIALUART4_RXDMA        NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 1, 1)
#define NVIC_PRIO_SERIALUART4              NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 1, 2)
#define NVIC_PRIO_SERIALUART5_TXDMA        NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 1, 0)
#define NVIC_PRIO_SERIALUART5_RXDMA        NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 1, 1)
#define NVIC_PRIO_SERIALUART5              NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 1, 2)
#define NVIC_PRIO_SERIALUART6_TXDMA        NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 1, 0)
#define NVIC_PRIO_SERIALUART6_RXDMA        NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 1, 1)
#define NVIC_PRIO_SERIALUART6              NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 1, 2)
#define NVIC_PRIO_SERIALUART7_TXDMA        NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 1, 0)
#define NVIC_PRIO_SERIALUART7_RXDMA        NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 1, 1)
#define NVIC_PRIO_SERIALUART7              NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 1, 2)
#define NVIC_PRIO_SERIALUART8_TXDMA        NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 1, 0)
#define NVIC_PRIO_SERIALUART8_RXDMA        NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 1, 1)
#define NVIC_PRIO_SERIALUART8              NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 1, 2)
#define NVIC_PRIO_I2C_ER                   NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 0, 0)
#define NVIC_PRIO_I2C_EV                   NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 0, 0)
#define NVIC_PRIO_USB                      NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 2, 0)
#define NVIC_PRIO_USB_WUP                  NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 1, 0)
#define NVIC_PRIO_MPU_DATA_READY           NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 0x0f, 0x0f)
#define NVIC_PRIO_MAG_DATA_READY           NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 0x0f, 0x0f)
#define NVIC_PRIO_CALLBACK                 NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 0x0f, 0x0f)
